#ifndef DEFINITIONS_H
#define DEFINITIONS_H

#include "bcm2835.h"

//#define PIN_RED_LIGHT RPI_V2_GPIO_P1_26
#define PIN_UP_BUTTON RPI_V2_GPIO_P1_22
#define PIN_YELLOW_LIGHT RPI_V2_GPIO_P1_05
#define PIN_DOWN_BUTTON RPI_V2_GPIO_P1_23
#define PIN_GREEN_LIGHT RPI_V2_GPIO_P1_24
#define PIN_GREEN_BUTTON RPI_V2_GPIO_P1_03
#define PIN_RFID_RESET RPI_V2_GPIO_P1_26
#define LCD_BL RPI_V2_GPIO_P1_07
#define LCD_RS RPI_V2_GPIO_P1_18
#define LCD_E RPI_V2_GPIO_P1_16
#define LCD_D4 RPI_V2_GPIO_P1_15
#define LCD_D5 RPI_V2_GPIO_P1_13
#define LCD_D6 RPI_V2_GPIO_P1_12
#define LCD_D7 RPI_V2_GPIO_P1_11

enum MEDIA_COMMAND_TYPE 
{ 
	MEDIA_OUT			= 48, 
	MEDIA_IN			= 49, 
	MEDIA_PERSON_OUT	= 50, 
	MEDIA_PERSON_IN		= 51, 
	MEDIA_TITLE			= 52, 
	NUM_COMMANDS 		= 53
};

#endif // DEFINITIONS_H

